### ISSUE TITLE
Code Builder - Arguments , Output and using namespaces

### ISSUE THREAD

**Issue by TTBDevAdmin** [OpenBotsAI/OpenBots.Studio#45]
Hi,
How can we pass data In and Out of the Code builder code ( arguments and output)?

also, compilation throws an error when we try to include the new namespace. 

![image](https://user-images.githubusercontent.com/54854919/99455496-eb9d8680-28f5-11eb-908e-72df687c86fc.png)

**Comment by openbots-ch** [comment]
The "Arguments" field in the Command should populate into the Main() args object similar to a command line invocation, and any console output should be put into the "Output" variable. The corresponding process parameters utilized for the input/output are linked below. I'm also noticing on a closer look that we are creating a temporary file in the assembly directory rather than in the project directory, which can cause issues when not running as administrator. 

Input:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.arguments?view=net-5.0
Output:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?view=net-5.0

This command is intended to bridge the gap for us while we integrate a full compiler such as Roslyn, and needs a bit of touching up. I'm going to add a work item to resolve the temporary file issue, inclusion of additional namespaces and test the Input/Output scenarios for the next release.

**Comment by TTBDevAdmin** [comment]
Thanks for the reply.
so in/out args can only be a string and not a complex type?

**compilation throws an error when we try to include the new namespace.**
How do we get around it?

**Comment by openbots-ch** [comment]
Unfortunately there isn't a way to add the additional assembly references in v1.1. In v1.2 we are adding as package manager that would allow users to reference additional assemblies and would likely resolve this issue. I will work with the team to test this specific scenario, and see what we can do to support additional input/output scenarios.

**Comment by TTBDevAdmin** [comment]
we are working on POC where we are processing one xlsx report and converting it into new xslx with pivot tables and formulas.
**Do you have support for formulas and Pivot tables in openbot?**
we were thinking of processing it through Run Custom Code command but it requires new packages and reference.

**Comment by openbots-ch** [comment]
Currently the Excel commands perform read operations on Values only. Were you to already know the formula you are able to write it into the cells/range and it will execute accordingly. I will add in a work item to create a "Formulas" options for the "Get" commands to allow for more advanced manipulation. 
Currently we do not have commands to manipulate Pivot Tables. I will add that to our roadmap. If you or your team are confident in C# creating and editing commands is a fairly easy process, and we could gladly assist if you would like to contribute commands to enable this functionality!

**Comment by openbots-ch** [comment]
@TTBDevAdmin, v1.2 has brought support for Formulas for both the Get Range and Get Cell commands. The inclusion of the Package Manager has laid the ground work for loading additional assemblies for execution. We will be evaluating the Run Custom Code command and integrating this new functionality in v1.3.

**Comment by openbots-ch** [comment]
Good Afternoon,

Following up here. As of v1.4.0 we now fully support C# scripting in the Studio, and allow for the building and running of created scripts. This functionality will replace Run Custom Code going forward, as it provides a much more fluid experience.
